### ISSUE TITLE
Issues from call on 24/2

### ISSUE THREAD

**Issue by datene** [h2nearme/h2near.me#50]
- ☑️ Offtakers location required hydrogen purity een vraagteken toevoegen met negens achter de komma, OVERAL.
- ☑️ Supply types, uitleg van applications per type. E.g. kan gebruikt worden voor auto's, etc.
- Overal duidelijker units bij zetten, per tijdseenheid etc. consistent per day aanhouden en aangeven
- ☑️ Vraagtekens toevoegen bij investment period en contract period
- ☑️ Data dump per scenario met uitleg en extra waarde datum laatste update, extra ENV variabele
- ☑️ Checkbox own_transport verplaatsen zodat het niet onder oxygen staat
- ☑️ Delimiters veranderen naar komma voor grote getallen, punt voor decimalen
- Mogelijk maken marker zelf te plaatsen voor locatie en daaruit de postcode, long, lat etc. te halen
- Disclaimer dat locatie een estimate is, disclaimer dat kosten estimates zijn
- Aangeven dat er geen rechten kunnen worden ontleend aan scenarios
- ☑️ Bij DRFTC ook een info bubbel
- Compression cost maakt op het moment geen gebruik van fallback waarde, wordt soms foutief op 0 gezet
- ☑️ Disclaimer bij proof of purity + proof of supply, uitleg van wat er dan precies verwacht wordt

**Comment by h2nearme** [comment]
/supplier_locations/features
- change "is this location currently available" to "is hydrogen currently available at this location"

**Comment by h2nearme** [comment]
**/supplier_locations/Supply**
- Add "Standard from electrolysis (∼98% / 1 nine)", "Electrolysis using ion transport membranes (99.8% / 2 nines), "Pure hydrogen (hydrogen purity ≥ 99.99% / 4 nines)", "High pure hydrogen (hydrogen purity ≥ 99.999% / 5 nines), "Ultrapure hydrogen (hydrogen purity ≥ 99.9999% / 6 nines)"
- Add examples per purity - standard: "Internal combustion engines for transportation; Residential/commercial combustion appliances (e.g. boilers, cookers, and similar applications) - ITMs: "Industrial fuel for power generation and heat generation except PEM fuel cell applications" - Pure: "PEM fuel cell for road vehicles" - High pure: "Aircraft and space-vehicle ground support systems except PEM fuel cell applications" - Ultrapure: "Aircraft and space-vehicle on-board propulsion and electrical energy requirements; off-road vehicles"

**Comment by h2nearme** [comment]
**/offtaker_locations/Requirements**
- Change "Required hydrogen volume in kilos per day" to "Required volume of hydrogen in kilograms per day"
- Add ? to "Investment period in years" with the following content: "The total upfront capital expenditure for the installation of a dedicated pipeline will be expressed in years hence we are looking for an investment period or asset lifetime to deduct the total capital expenditure by. If unsure, use the average lifetime of 25 years of a dedicated pipeline."
- Add ? to "Contract period in years" with the following content: "The total operational expenditure for the installation of a dedicated pipeline will be expressed in years hence we are looking for an expected contract period to deduct the total operational expenditure by. If unsure, use an average contract period of 10 years."
